openapi: 3.0.2
info:
  title: T-Mess
  description: Message service
  version: '1.0'
paths:
  /message/send:
    post:
      tags:
      - Messages
      summary: Send message
      operationId: send_message_message_send_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /message/update/{message_id}:
    put:
      tags:
      - Messages
      summary: Send message
      operationId: update_message_message_update__message_id__put
      parameters:
      - name: message_id
        in: path
        required: true
        schema:
          type: string
          title: Message Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageText'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Invalid message_id format
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /message/delete/{message_id}:
    delete:
      tags:
      - Messages
      summary: Send message
      operationId: delete_message_message_delete__message_id__delete
      parameters:
      - name: message_id
        in: path
        required: true
        schema:
          type: string
          title: Message Id
      responses:
        '200':
          description: Successful Response
        '400':
          description: Invalid message_id format
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /message/history:
    get:
      tags:
      - Messages
      summary: Get chat history
      operationId: get_chat_history_message_history_get
      parameters:
      - name: chat_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: uuid
          - type: 'null'
          title: Chat Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageResponse'
                title: Response Get Chat History Message History Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /message/find:
    get:
      tags:
      - Messages
      summary: Find text in message
      operationId: find_text_in_message_message_find_get
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
          title: Text
      - name: chat_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
            format: uuid
          - type: 'null'
          title: Chat Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageResponse'
                title: Response Find Text In Message Message Find Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Message:
      properties:
        text:
          type: string
          minLength: 1
          title: Text
        chat_id:
          type: string
          format: uuid
          title: Chat Id
        sender:
          type: string
          minLength: 1
          title: Sender
        sending_time:
          type: string
          format: date-time
          title: Sending Time
      type: object
      required:
      - text
      - chat_id
      - sender
      - sending_time
      title: Message
    MessageResponse:
      properties:
        text:
          type: string
          minLength: 1
          title: Text
        chat_id:
          type: string
          format: uuid
          title: Chat Id
        sender:
          type: string
          minLength: 1
          title: Sender
        sending_time:
          type: string
          format: date-time
          title: Sending Time
        message_id:
          type: string
          title: Message Id
      type: object
      required:
      - text
      - chat_id
      - sender
      - sending_time
      - message_id
      title: MessageResponse
    MessageText:
      properties:
        text:
          type: string
          minLength: 1
          title: Text
      type: object
      required:
      - text
      title: MessageText
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
servers:
- url: http://localhost:8001
