version: "3.9"

services:
  user_service:
    build:
      context: user_service
      dockerfile: Dockerfile
    container_name: user_service
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - messenger-net
    volumes:
      - ./user_service:/work_dir
    depends_on:
      init_db:
        condition: service_completed_successfully

  message_service:
    build:
      context: message_service
      dockerfile: Dockerfile
    container_name: message_service
    restart: unless-stopped
    ports:
      - "8001:8000"
    networks:
      - messenger-net
    volumes:
      - ./message_service:/work_dir
    depends_on:
      init_db:
        condition: service_completed_successfully

  init_db:
    build:
      context: init_db
      dockerfile: Dockerfile
    container_name: init_db
    restart: on-failure
    networks:
      - messenger-net
    volumes:
      - ./init_db:/work_dir
    depends_on:
      postgres:
        condition: service_started
      mongo:
        condition: service_healthy
    entrypoint: ["python3", "main.py"]

  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger
      PG_DATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - messenger-net
    volumes:
      - db_volume:/data/postgres

  mongo:
    container_name: mongo
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - messenger-net
    volumes:
      - mongo_volume:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      timeout: 3s
      retries: 5

networks:
  messenger-net:
    driver: bridge

volumes:
  db_volume:
    driver: local
  mongo_volume:
    driver: local