openapi: 3.0.2
info:
  title: T-Mess
  description: Message service
  version: '1.0'
paths:
  /message/send:
    post:
      tags:
      - Messages
      summary: Send message
      operationId: send_message_message_send_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      responses:
        '200':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /message/history:
    get:
      tags:
      - Messages
      summary: Get chat history
      operationId: get_chat_history_message_history_get
      parameters:
      - name: chat_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
          title: Chat Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageResponse'
                title: Response Get Chat History Message History Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Message:
      properties:
        sender:
          type: string
          minLength: 1
          title: Sender
        sending_time:
          type: string
          format: date-time
          title: Sending Time
        text:
          type: string
          minLength: 1
          title: Text
        chat_id:
          type: string
          format: uuid
          title: Chat Id
      type: object
      required:
      - sender
      - sending_time
      - text
      - chat_id
      title: Message
    MessageResponse:
      properties:
        sender:
          type: string
          minLength: 1
          title: Sender
        sending_time:
          type: string
          format: date-time
          title: Sending Time
        text:
          type: string
          minLength: 1
          title: Text
      type: object
      required:
      - sender
      - sending_time
      - text
      title: MessageResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
servers:
- url: http://localhost:8001
